disabled_rules: # rule identifiers to exclude from running
  - class_delegate_protocol
  - compiler_protocol_init
  - dynamic_inline
  - function_parameter_count
  - implicit_getter
  - discarded_notification_center_observer
  - nesting

# rule identifiers to opt in
opt_in_rules:
  - file_header
  - closure_spacing
  - closure_end_indentation
  - conditional_returns_on_newline
  - implicitly_unwrapped_optional
  - missing_docs
  - force_unwrapping

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift

force_cast: error 
force_unwrapping: warning # implicitly
force_try:
  severity: warning # explicitly

colon: 
  severity: error

line_length:
   error: 120

file_header:
  required_string: Brastlewark
  severity: error

identifier_name:
  min_length: # warning and error
    error: 3
  max_length: # warning and error
    warning: 38
    error: 40

vertical_whitespace: 
  max_empty_lines: 1
  severity: error

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

file_length:
  warning: 480
  error: 600

implicitly_unwrapped_optional:
  mode: allExceptIBOutlets

function_body_length:
  - 120
  - 150

large_tuple:
  warning: 2
  error: 3

  conditional_returns_on_newline:
  severity: error

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
