# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Brastlewark' do
  
  use_frameworks!

  # Pods for Brastlewark
  pod 'SwiftLint'
  pod 'Alamofire', '~> 5.2'
  pod 'lottie-ios'

  target 'BrastlewarkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BrastlewarkUITests' do
    # Pods for testing
  end

end
